- menu_name: "Links"

#- name: "Contact"
#  url: "/contact/"
#  class: "services-contact"
#  title: "Contact"

- name: "Feed RSS"
  url: "/feed.xml"
  class: "rss-link"
  title: "Fedd RSS"

#- name: "sitemap.xml"
#  url: "/sitemap.xml"
#  class: "sitemap-link"
#  title: "Sitemap for Google Webmastertools"
